// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzsGXT5AapockbA05lKN_zod-lF9DsToA',
    appId: '1:1082789317708:web:5fa0976dccfa602d9578e9',
    messagingSenderId: '1082789317708',
    projectId: 'mementoapp-a5c3f',
    authDomain: 'mementoapp-a5c3f.firebaseapp.com',
    storageBucket: 'mementoapp-a5c3f.firebasestorage.app',
    measurementId: 'G-W4T94R1FEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-jAKSR9tqwX1Cq9qX8-FU2NhxvWow5BM',
    appId: '1:1082789317708:android:6421dab8983394cf9578e9',
    messagingSenderId: '1082789317708',
    projectId: 'mementoapp-a5c3f',
    storageBucket: 'mementoapp-a5c3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB299cK6lEtWp-JhcVNhG4aewHGFNZBsmE',
    appId: '1:1082789317708:ios:4094c4e4d1a96cfa9578e9',
    messagingSenderId: '1082789317708',
    projectId: 'mementoapp-a5c3f',
    storageBucket: 'mementoapp-a5c3f.firebasestorage.app',
    iosBundleId: 'com.example.lifeTracking',
  );
}
