final List<String> interests = [
  "Travel",
  "Dates / Relationships",
  "Family",
  "Friends",
  "Health & Fitness",
  "Sports",
  "Music",
  "Movies & TV",
  "Books & Literature",
  "Education",
  "Self-Development",
  "Finance & Investing",
  "Career / Work",
  "Food & Cooking",
  "Gaming",
  "Art & Design",
  "Photography",
  "Technology",
  "Science",
  "Nature & Outdoors",
  "Pets & Animals",
  "Fashion & Style",
  "Shopping",
  "Meditation & Mindfulness",
  "Politics & Society",
  "Culture & Traditions",
  "Languages",
  "DIY & Crafts",
  "Adventure",
  "Volunteering / Charity",
  "Cars & Vehicles",
  "Home & Gardening",
  "Spirituality",
  "Movies Making / Video Editing",
  "Other",
];
